### ISSUE TITLE
Improve attacks

### ISSUE THREAD

**Issue by jhideki** [jonathan-ami/pixel-platformer#39]
- Add feedback when attacks hit (e.g., enemy blood, knockback, damage counter etc...)
- Fix attack range
- Fix point of impact (enemy should only receive damage when hit by the tip of the spear)
- Add cooldown for attacks (so we can't spam light and heavy attacks)

**Comment by pgchmp22** [comment]
also
1.) cant move while attacking 
2.) enemy dying time is super delayed
